name: game
description: Classic Sokoban the game using flutter framework

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  swipedetector: ^1.2.0
  provider: ^3.2.0
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  path_provider: any
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.3
  firebase_database: ^3.1.1
  simple_animations: ^1.3.4
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
