name: game
description: Classic Sokoban the game using flutter framework

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  swipedetector: ^1.2.0
  provider: ^3.2.0
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.9.0
  build_runner: ^1.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
